<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
    <RootNamespace>FastFill.App</RootNamespace>
    <AssemblyName>FastFill</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <AppxPackageSigningEnabled>false</AppxPackageSigningEnabled>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FastFill.Core/FastFill.Core.csproj" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="OpenCvSharp4.runtime.win.slim" />
    <PackageReference Include="SkiaSharp.Views.WinUI" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\AppIcon.png" />
    <Content Include="Assets\Square44x44Logo.png" />
    <Content Include="Assets\Square150x150Logo.png" />
    <Content Include="Assets\StoreLogo.png" />
  </ItemGroup>
</Project>

