<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FastFill.Core</RootNamespace>
    <AssemblyName>FastFill.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
</Project>

